config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'aboutus', to: 'pages#aboutus'
  get 'contact', to: 'pages#contact'

  resources :checkouts,  only: [:new, :create, :show]

  resource :shopping_cart, path: 'cart', only: [:show, :destroy]
  resources :shopping_cart_items, path: 'items', only: [:create, :update, :destroy]

  resources :users, only: [:show, :edit, :destroy, :destroy]
  resources :products
  resources :orders
  root "pages#index"
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
	acts_as_shopping_cart

	def taxes
		0
	end

	def shipping_cost
		Money.new(1000)
	end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
	def show; end

	def destroy
		@shopping_cart.clear
		redirect_to root_path
	end
end

app/views/shopping_carts/_shopping_cart_item.html.erb
<tr>
  <td><%= shopping_cart_item.item.name %></td>
  <td><%= number_to_currency(shopping_cart_item.item.price)%></td>
  <td><%= form_tag(shopping_cart_item_path(id: shopping_cart_item.id), method: :patch) do%>
      <%= select_tag :quantity, options_for_select(1..shopping_cart_item.item.quantity, "#{shopping_cart_item.quantity}"), { onchange: 'this.form.submit()' }%><%end%></td>
  <td><%= number_to_currency(shopping_cart_item.subtotal)%></td>
  <td><%= button_to shopping_cart_item_path(id: shopping_cart_item.id), method: :delete, class: 'btn btn-to-link' do %>
    <i class="fa-solid fa-trash-can"></i>
    <%end%></td>
</tr>

app/views/shopping_carts/show.html.erb
<h1>Shopping Cart</h1>

<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Item</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => 'shopping_cart_item', 
       :collection => @shopping_cart.shopping_cart_items%>
    </tbody>
  </table>
</div>

<%if @shopping_cart.shopping_cart_items.present? %>
  <%= link_to 'Checkout', new_order_path, class: 'btn btn-outline-primary' %>
<%else%>
  <p>Your cart is empty.</p>
<%end%>