config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'aboutus', to: 'pages#aboutus'
  get 'contact', to: 'pages#contact'

  resources :checkouts,  only: [:new, :create, :show]

  resource :shopping_cart, path: 'cart', only: [:show, :destroy]
  resources :shopping_cart_items, path: 'items', only: [:create, :update, :destroy]

  resources :users, only: [:show, :edit, :destroy, :destroy]
  resources :products
  resources :orders
  root "pages#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :orders
  
  enum role: [:customer, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :customer
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find_by(id: params[:id])
	end
end

app/views/users/show.html.erb
<h1>Welcome <%= current_user.email%></h1>
<p>Here are your order history</p>

<%if current_user.orders.any? %>
<div class="row row-cols-auto px-2">	
	<% current_user.orders.each do |order| %>
	<div class="col-md-2 p-2" > 
		<div class="card bg-light h-100 mb-3" style="width: 13rem;">
			<%= link_to order_path(order) do%>
			Name: <%= order.name %><br>
			<%end%>
			Email Ref: <%= order.email%><br>
			Payment: RM <%= number_to_currency(order.total, unit:"RM ")%><br>
		</div>
	</div>
	<%end%><br>	
</div>
<%end%>
<% if admin? %>
<p><%= link_to 'Order histories', orders_path(@orders), class: 'btn btn-outline-secondary' %></p>
<%end%>