config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'aboutus', to: 'pages#aboutus'
  get 'contact', to: 'pages#contact'

  resources :checkouts,  only: [:new, :create, :show]

  resource :shopping_cart, path: 'cart', only: [:show, :destroy]
  resources :shopping_cart_items, path: 'items', only: [:create, :update, :destroy]

  resources :users, only: [:show, :edit, :destroy, :destroy]
  resources :products
  resources :orders
  root "pages#index"
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :order_items, as: :orderable
	has_many_attached :photos

	CATEGORIES = %w[keychain bracelet necklace earrings]

	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		if params[:category]
			@products = Product.where("category LIKE ? OR description LIKE ?",
				"%#{params[:category]}%", "%#{params[:category]}%")
		else
			@products = Product.all
		end
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.create(product_params)
		if @product.save
			redirect_to products_path(@products)
		else
			render :new
		end
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])	
	end

	def update
		@product = Product.find(params[:id])
		@product.update(product_params)
		if @product.save
			redirect_to product_path(@product)
		else
			render :edit
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to root_path
	end

	def product_params
		params.require(:product).permit(:name, :category, :description, :price, :quantity, photos: [])
	end
end

app/views/products/_product_form.html.erb
<div class="container w-80 border border-5 rounded-5 p-4" style="background: #cd9cf2">
	<%= form_with model: @product do |f|%>
		<%= f.collection_select(:category, Product::CATEGORIES, :to_s, :humanize, { include_blank: "Select category"})%>		
		<br><%= f.label :photos%>
		<br><%= f.file_field :photos, multiple: true%>
		<br><%= f.text_field :name, placeholder: "Name"%>
		<br><%= f.text_area :description, placeholder: "Description here"%>
		<br><%= f.number_field :price, placeholder: "Price in RM", min: 1%>
		<br><%= f.number_field :quantity, placeholder: "Quantity", min: 1%>
		<br>

		<% if @product.new_record? %>
				<%= f.submit'Create'%>
		<% else %>
				<%= f.submit 'Update'%>
		<% end %>
	<%end%>
</div>

app/views/products/edit.html.erb
<h2>Edit product details</h2>
<%= render 'product_form'%>

app/views/products/index.html.erb
<form action="<%= products_path%>" class="d-flex row align-items-end px-1 my-1">
  <div class="col-auto">
    <input class="form-control" type="text" placeholder="Search by category" name="category">
  </div>
  <div class="col-auto">
    <button class="btn btn-outline-primary" type="Search">Search</button>
  </div>
</form>

<%if @products.any?%>
<div class="row row-cols-auto px-2">
  <% @products.each do |product|%>
  <div class="col-md-2 p-2" > 
    <div class="card bg-light h-100 mb-3" style="width: 13rem;">
    <%= link_to product_path(product), class: 'no-underline' do%>
        <%if product.photos.attached?%>
          <i class="fa-solid fa-star"></i>
            <%= product.name%><br>
            <%= image_tag product.photos.first, width: 150, height: 150 %>
        <%end%> 
    <%end%>      
        <div class="card-body">
          <p class="card-text"><%= number_to_currency(product.price, unit:"RM ") %></p>
        </div>
    </div>    
  </div>   
  <%end%> 
</div>
<%else%>
  <p>No Products Found.</p>  
<%end%>

<% if admin? %>
  <%= link_to 'Create new product', new_product_path(@products), class: 'btn btn-outline-primary'%><br>
<%end%>
<!-- <%#= link_to 'Homepage', root_path%> -->

app/views/products/new.html.erb
<h2>Create product details</h2>
<%= render 'product_form'%>

app/views/products/show.html.erb
<h1><%= @product.name%></h1>

<%if @product.photos.attached? %>
		<% @product.photos.each do |photo|%>
			<%= link_to rails_blob_path(photo, disposition: "attachment") do %>	
			<%end%>
		<%= image_tag photo, width: 400, height: 400 %>		
		<%end%>
<%end%><br>

	
	<p>Category: <%= @product.category%></p>
	<p>Product Details: <%= @product.description%></p>
	<p><%= number_to_currency(@product.price, unit:"RM ") %></p>
	<p>Available Quantity: <%= @product.quantity%></p>
	<br>
	
<div class="row questions bg-light p-5">
	<div class="col-md-1 icon">
	<i class="fa-brands fa-rocketchat questions-icon"></i>
	</div>
	<div class="col-md-11 text">
	Have a question about our products at E-Store? Feel free to contact our representatives via live chat or email.
	</div>
</div>

<div class="delivery my-4">
	<p class="font-weight-bold mb-0"><span><i class="fa-solid fa-truck"></i></span> <b>Delivery done in 3 days from date of purchase</b> </p>
	<p class="text-secondary">Order now to get this product delivery</p>
</div>
<div class="delivery-options my-4">
	<p class="font-weight-bold mb-0"><span><i class="fa-solid fa-filter"></i></span> <b>Delivery options</b> </p>
	<p class="text-secondary">View delivery options here</p>
</div>
<%= link_to shopping_cart_path do%>
<i class="fa-solid fa-cart-shopping">Show Cart Page</i>
<%end%>
<br><br>


<%= button_to 'Add to cart', shopping_cart_items_path(item_id: @product, class: @product.class), class: 'btn btn-dark btn-lg w-100' %>

<section style="background-color: #DEC0F1;">
<% if admin? %>
	<%= link_to 'Edit', edit_product_path(@product), class: 'no-underline btn btn-outline-danger btn-sm'%>

	<%= link_to 'Delete', product_path(@product), 
		data: {turbo_method: :delete,
		turbo_confirm: "Are you sure?"}, class: 'no-underline btn btn-outline-danger btn-sm'%>
<%end%>
</section>