config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'aboutus', to: 'pages#aboutus'
  get 'contact', to: 'pages#contact'

  resources :checkouts,  only: [:new, :create, :show]

  resource :shopping_cart, path: 'cart', only: [:show, :destroy]
  resources :shopping_cart_items, path: 'items', only: [:create, :update, :destroy]

  resources :users, only: [:show, :edit, :destroy, :destroy]
  resources :products
  resources :orders
  root "pages#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sixstonejewellery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"%>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-light px-3" style="background-color: #DEC0F1;">
    <div>
      <%= link_to image_tag('logo.png', width: 60, height: 50), root_path%>
    </div>
  
  <div>
    <%= link_to products_path(@products), class: 'no-underline' do%>
    Shop
    <%end%>
  </div>
  <div>
    <%= link_to aboutus_path, class: 'no-underline' do%>
    About Us
    <%end%>
  </div>
  <div>
    <%= link_to contact_path, class: 'no-underline' do%>
    Contact Us
    <%end%>
  </div>

  <div>
    <%= link_to shopping_cart_path do%>
      <i class="fa-solid fa-cart-shopping"></i>
    <%end%>
  </div>

  <div class="dropdown">
    <%if user_signed_in?%>
      <h3 class="btn btn-outline-info dropdown-toggle" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
        <%= current_user.email%>
      </h3>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink"> 
        <li><%= link_to 'Dashboard', user_path(current_user), class: 'no-underline' %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete}, class: 'no-underline' %></li>
    <%else%> 
        <li class="btn btn-outline-info"><%= link_to 'Login', new_user_session_path, class: 'no-underline'%></li>
        <li class="btn btn-outline-info"><%= link_to 'Sign Up', new_user_registration_path, class: 'no-underline'%></li>
      </ul>
    <%end%>
  </div>
  </nav>

<%if notice%>  
  <p class="notice"><%= notice %></p>
<%end%>

    <%= yield %>
    <script src="https://kit.fontawesome.com/aaba9ef673.js" crossorigin="anonymous"></script>

  <footer class=" text-center text-white mt-auto" style="background-color: #7161EF;">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright:
    <a class="text-white" href="#">6stone.com</a>
  </div>
  <!-- Copyright -->
</footer>
  </body>

</html>